### ISSUE TITLE
Relax rule regarding braces for CoffeeScript

### ISSUE THREAD

**Issue by Koronen** [studentcompetitions/guides#17]
Yanked from #23:

> @koronen: On second thought, I think we might want to tweak this rule when dealing with JavaScript/CoffeeScript, especially when used to construct simple objects passed as parameters like on line 76 below. I think I'd prefer not adding any more spaces to that line.
>
>     new Challenge().$delete({id: id}, success, failure)
> @linduxed: Well, we do have a different set of rules for CoffeeScript already (eg. in Ruby we advocate the use of &&, while in CoffeeScript we use and) so if this is a commonly reoccurring construct, then maybe it would make sense to have that rule.
>
> All I would care for is consistency and that the people who code Coffee agree that the rule makes sense.

**Comment by maxnordlund** [comment]
This is really old, let's close this for now, and if we want to reevaluate this, we can make a new issue or just repoen this one.
