### ISSUE TITLE
We should make this guides-repo a proper wiki-repo

### ISSUE THREAD

**Issue by Burgestrand** [studentcompetitions/guides#30]
This would allow us to have footers/sidebars and easier linking between wiki pages.

@studentcompetitions/infrastructure

**Comment by Frost** [comment]
Wouldn't that mean we sort of need to host it somewhere as well?

**Comment by Burgestrand** [comment]
GitHub wiki!

**Comment by Frost** [comment]
I have now enabled [wiki](https://github.com/studentcompetitions/guides/wiki) functionality on this repo.
